// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onneyfycttntqcbvytyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubmV5ZnljdHRudHFjYnZ5dHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mjc2NDAsImV4cCI6MjA2NDMwMzY0MH0.dtDW2TH8irX5uVqRCGyf_UfEly2UfVkCOY0ABg3z04s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);